### ISSUE TITLE
Latest version of star rating plugin is showing warning instead of content

### ISSUE THREAD

**Issue by gurjyot** [q2amarket/q2am-star-ratings#4]
The latest version of this plugin is showing warnings.
Warning: require_once(/home3/name/public_html/abcd/qa-plugin/q2am-star-ratings/q2am_star_ratings_class.php): failed to open stream: No such file or directory in /home3/name/public_html/abcd/qa-include/qa-base.php(510) : eval()'d code on line 160

Fatal error: require_once(): Failed opening required '/home3/name/public_html/abcd/qa-plugin/q2am-star-ratings/q2am_star_ratings_class.php' (include_path='.:/opt/php54/lib/php') in /home3/name/public_html/abcd/qa-include/qa-base.php(510) : eval()'d code on line 160

But I am using this plugin's previous version in other websites and that works perfect. Please fix the issue.

**Comment by q2amarket** [comment]
Can you please check the location and see if `q2am_star_ratings_class.php` is there? This is simply saying file doesn't exits.

**Comment by gurjyot** [comment]
I just checked this and the file is surely there. Here is a screenshot of the error I am getting. 

![star](https://cloud.githubusercontent.com/assets/6462850/7971435/5fb1c27e-0a62-11e5-9d48-d4eebfc3a7dd.png)

This installation of Q2A and star rating plugin is new so there is no chance that some other plugin is causing problem.

**Comment by gurjyot** [comment]
any update on this plugin...??

**Comment by q2amarket** [comment]
There was an issue with updated Q2A core functions. I have fixed the issue and pushed all updates.
